os: Visual Studio 2017

platform: x64

configuration: Release

init:
  - git config --global core.autocrlf input

before_build:
  - mkdir build
  - cd build
  - cmake -A%PLATFORM% ..
  - cd ..

build:
  project: build\red3.sln
  parallel: true
  verbosity: normal        # quiet|minimal|normal|detailed

test_script:
  - cd build\bin\Release
  - cmd: red3tests.exe
  - cd ..\..\..
