os: Visual Studio 2017

platform: x64

init:
  - git config --global core.autocrlf input

before_build:
  - mkdir build
  - cd build
  - cmake -A%PLATFORM% -DCMAKE_BUILD_TYPE=Release ..

build:
  project: build\red3.sln
  parallel: true
  verbosity: normal        # quiet|minimal|normal|detailed
